spring.datasource.url=jdbc:mysql://localhost:3306/api_recebe_dados
spring.datasource.username=root
spring.datasource.password=Gaston0118

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud-name=${C_NAME}
cloudinary.api-key=${C_KEY}
cloudinary.api-secret=${C_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
