spring.datasource.url=jdbc:mysql://localhost:3306/api_recebe_dados
spring.datasource.username=root
spring.datasource.password=Gaston0118

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud-name=dcuhykmck
cloudinary.api-key=786146217811398
cloudinary.api-secret=Bh0lw_-xxokp92PIXQb8GtPNrDw

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xa86398@gmail.com
spring.mail.password=hzkx omcv midy msyo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
